before_install:
- sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
- sudo apt-get update -qq
install:
- pip install coveralls
language: python
env:
- SERVER=apache
- SERVER=nginx
python:
- 2.7
- 3.4
script:
- echo 
- coverage run -m unittest discover -v
after_success:
- coveralls
